
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:9001", "s201:9002", "s301:9003", "s401:9004", "s501:9005", "s601:9006", "s701:9007", "s801:9008", "s901:9009", "s1001:9010", "s1101:9011"]
  client: # each line is a partition
    - ["c101", "c201", "c301", "c401", "c501", "c601", "c701", "c801", "c901", "c1001"]

# site_name - process_name map
process:
  s101: localhost
  s201: localhost
  s301: localhost
  s401: localhost
  s501: localhost
  s601: localhost
  s701: localhost
  s801: localhost
  s901: localhost
  s1001: localhost
  s1101: localhost
  c101: localhost
  c201: localhost
  c301: localhost
  c401: localhost
  c501: localhost
  c601: localhost
  c701: localhost
  c801: localhost
  c901: localhost
  c1001: localhost

# process_name - host_addr map
host:
  localhost: 127.0.0.1         