
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:9140", "s201:9141", "s301:9142", "s401:9143", "s501:9144", "s601:9145", "s701:9147"]
  client: # each line is a partition
    - ["c101", "c201", "c301", "c401", "c501", "c601", "c701", "c801", "c901", "c1001",
      "c1101", "c1201", "c1301", "c1401", "c1501", "c1601", "c1701", "c1801", "c1901", "c2001",
      "c2101", "c2201", "c2301", "c2401", "c2501", "c2601", "c2701", "c2801", "c2901", "c3001",
      "c3101", "c3201", "c3301", "c3401", "c3501", "c3601", "c3701", "c3801", "c3901", "c4001",
      "c4101", "c4201", "c4301", "c4401", "c4501", "c4601", "c4701", "c4801", "c4901", "c5001"]

# site_name - process_name map
process:
  s101: localhost
  s201: localhost
  s301: localhost
  s401: localhost
  s501: localhost
  s601: localhost
  s701: localhost
  c101: localhost
  c201: localhost
  c301: localhost
  c401: localhost
  c501: localhost
  c601: localhost
  c701: localhost
  c801: localhost
  c901: localhost
  c1001: localhost
  c1101: localhost
  c1201: localhost
  c1301: localhost
  c1401: localhost
  c1501: localhost
  c1601: localhost
  c1701: localhost
  c1801: localhost
  c1901: localhost
  c2001: localhost
  c2101: localhost
  c2201: localhost
  c2301: localhost
  c2401: localhost
  c2501: localhost
  c2601: localhost
  c2701: localhost
  c2801: localhost
  c2901: localhost
  c3001: localhost
  c3101: localhost
  c3201: localhost
  c3301: localhost
  c3401: localhost
  c3501: localhost
  c3601: localhost
  c3701: localhost
  c3801: localhost
  c3901: localhost
  c4001: localhost
  c4101: localhost
  c4201: localhost
  c4301: localhost
  c4401: localhost
  c4501: localhost
  c4601: localhost
  c4701: localhost
  c4801: localhost
  c4901: localhost
  c5001: localhost

# process_name - host_addr map
host:
  localhost: 127.0.0.1         
  # h01: 127.0.0.1
  # h02: 127.0.0.1
  # h03: 127.0.0.1
  # h04: 127.0.0.1