
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:12001", "s201:12002", "s301:12003", "s401:12004", "s501:12005", "s601:12006", "s701:12007", "s801:12008", "s901:12009", "s1001:12010", "s1101:12011", "s1201:12012", "s1301:12013", "s1401:12014", "s1501:12015", "s1601:12016", "s1701:12017", "s1801:12018", "s1901:12019", "s2001:12020", "s2101:12021"]
  client: # each line is a partition
    - ["c101", "c201", "c301", "c401", "c501", "c601", "c701", "c801", "c901", "c1001",
      "c1101", "c1201", "c1301", "c1401", "c1501", "c1601", "c1701", "c1801", "c1901", "c2001",
      "c2101", "c2201", "c2301", "c2401", "c2501", "c2601", "c2701", "c2801", "c2901", "c3001",
      "c3101", "c3201", "c3301", "c3401", "c3501", "c3601", "c3701", "c3801", "c3901", "c4001",
      "c4101", "c4201", "c4301", "c4401", "c4501", "c4601", "c4701", "c4801", "c4901", "c5001",
      "c5101", "c5201", "c5301", "c5401", "c5501", "c5601", "c5701", "c5801", "c5901", "c6001",
      "c6101", "c6201", "c6301", "c6401", "c6501", "c6601", "c6701", "c6801", "c6901", "c7001",
      "c7101", "c7201", "c7301", "c7401", "c7501", "c7601", "c7701", "c7801", "c7901", "c8001",
      "c8101", "c8201", "c8301", "c8401", "c8501", "c8601", "c8701", "c8801", "c8901", "c9001"]

# site_name - process_name map
process:
  s101: localhost
  s201: localhost
  s301: localhost
  s401: localhost
  s501: localhost
  s601: localhost
  s701: localhost
  s801: localhost
  s901: localhost
  s1001: localhost
  s1101: localhost
  s1201: localhost
  s1301: localhost
  s1401: localhost
  s1501: localhost
  s1601: localhost
  s1701: localhost
  s1801: localhost
  s1901: localhost
  s2001: localhost
  s2101: localhost
  c101: localhost
  c201: localhost
  c301: localhost
  c401: localhost
  c501: localhost
  c601: localhost
  c701: localhost
  c801: localhost
  c901: localhost
  c1001: localhost
  c1101: localhost
  c1201: localhost
  c1301: localhost
  c1401: localhost
  c1501: localhost
  c1601: localhost
  c1701: localhost
  c1801: localhost
  c1901: localhost
  c2001: localhost
  c2101: localhost
  c2201: localhost
  c2301: localhost
  c2401: localhost
  c2501: localhost
  c2601: localhost
  c2701: localhost
  c2801: localhost
  c2901: localhost
  c3001: localhost
  c3101: localhost
  c3201: localhost
  c3301: localhost
  c3401: localhost
  c3501: localhost
  c3601: localhost
  c3701: localhost
  c3801: localhost
  c3901: localhost
  c4001: localhost
  c4101: localhost
  c4201: localhost
  c4301: localhost
  c4401: localhost
  c4501: localhost
  c4601: localhost
  c4701: localhost
  c4801: localhost
  c4901: localhost
  c5001: localhost
  c5101: localhost
  c5201: localhost
  c5301: localhost
  c5401: localhost
  c5501: localhost
  c5601: localhost
  c5701: localhost
  c5801: localhost
  c5901: localhost
  c6001: localhost
  c6101: localhost
  c6201: localhost
  c6301: localhost
  c6401: localhost
  c6501: localhost
  c6601: localhost
  c6701: localhost
  c6801: localhost
  c6901: localhost
  c7001: localhost
  c7101: localhost
  c7201: localhost
  c7301: localhost
  c7401: localhost
  c7501: localhost
  c7601: localhost
  c7701: localhost
  c7801: localhost
  c7901: localhost
  c8001: localhost
  c8101: localhost
  c8201: localhost
  c8301: localhost
  c8401: localhost
  c8501: localhost
  c8601: localhost
  c8701: localhost
  c8801: localhost
  c8901: localhost
  c9001: localhost

# process_name - host_addr map
host:
  localhost: 127.0.0.1         
  # h01: 127.0.0.1
  # h02: 127.0.0.1
  # h03: 127.0.0.1
  # h04: 127.0.0.1